/**
 * Miliastra Wonderland Node Graph - Flow Control Nodes
 * Autogenerated from specification reference.
 * Total nodes: 2
 */

export const FLOW_NODES = [
  {
    "id": "flow_multiple_branches",
    "name": "Multiple Branches",
    "category": "flow",
    "folder": "I. General",
    "description": "Accepts one input parameter as the control expression (supports Integer or String). Branches into multiple paths based on its value. When the value on an Output Pin equals the control expression, execution continues along that Output Pin. If no pin matches, the `[Default]` pin is taken.",
    "inputs": [
      {
        "name": "Control Expression",
        "type": "generic",
        "description": "Only supports `[int]` or `[string]`",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      }
    ],
    "outputs": [],
    "execIn": true,
    "execOut": [
      {
        "name": "Branch 0",
        "pinType": "exec"
      },
      {
        "name": "Branch 1",
        "pinType": "exec"
      },
      {
        "name": "Branch 2",
        "pinType": "exec"
      },
      {
        "name": "Default",
        "pinType": "exec"
      }
    ],
    "canAddDynamicBranches": true
  },
  {
    "id": "flow_double_branch",
    "name": "Double Branch",
    "category": "flow",
    "folder": "I. General",
    "description": "Branches into `True` or `False` based on the evaluated condition. When the Boolean is `True`, the `[True]` execution flow runs; when it is `False`, the `[False]` execution flow runs.",
    "inputs": [
      {
        "name": "Condition",
        "type": "bool",
        "defaultVal": "True",
        "options": [
          "True",
          "False"
        ]
      }
    ],
    "outputs": [],
    "execIn": true,
    "execOut": [
      {
        "name": "Yes",
        "pinType": "execYes"
      },
      {
        "name": "No",
        "pinType": "execNo"
      }
    ]
  }
];
