/**
 * Miliastra Wonderland Node Graph - Operation Nodes
 * Autogenerated from specification reference.
 * Total nodes: 62
 */

export const OPERATION_NODES = [
  {
    "id": "op_enumerations_equal",
    "name": "Enumerations Equal",
    "category": "operation",
    "folder": "I. General",
    "description": "After confirming the Enumeration type, determines whether the two input values are equal.",
    "inputs": [
      {
        "name": "Enumeration 1",
        "type": "generic",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      },
      {
        "name": "Enumeration 2",
        "type": "generic",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "bool",
        "description": "Output `True` if equal, `False` if not equal"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_assembly_list",
    "name": "Assembly List",
    "category": "operation",
    "folder": "I. General",
    "description": "Assembles multiple Input Parameters of the same type (up to 100) into a single List.",
    "inputs": [
      {
        "name": "0~99",
        "type": "generic",
        "description": "Assembles up to 100 parameters into a list",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      }
    ],
    "outputs": [
      {
        "name": "List",
        "type": "generic",
        "description": "The assembled list",
        "hasGear": true
      }
    ],
    "execIn": false,
    "execOut": false,
    "canAddDynamicInputs": true
  },
  {
    "id": "op_equal",
    "name": "Equal",
    "category": "operation",
    "folder": "I. General",
    "description": "Determines whether two inputs are equal. Some Parameter Types have special comparison rules: **Floating Point Numbers:** Compared using approximate equality. When the difference between two Floating Point Numbers is less than an extremely small value, the two numbers are considered equal. Example: `2.0000001` and `2.0` are considered equal. **3D Vector:** The x, y, and z components are compared using Floating Point approximate equality.",
    "centerSymbol": "=",
    "inputs": [
      {
        "name": "Input 1",
        "type": "generic",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      },
      {
        "name": "Input 2",
        "type": "generic",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "bool",
        "description": "Output `True` if equal, `False` if not equal"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_data_type_conversion",
    "name": "Data Type Conversion",
    "category": "operation",
    "folder": "I. General",
    "description": "Converts input parameter types to another type for output. For specific rules, see Basic Concepts - [Conversion Rules Between Basic Data Types]. Floating point numbers are rounded to integers when converted.",
    "inputs": [
      {
        "name": "Input",
        "type": "generic",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      }
    ],
    "outputs": [
      {
        "name": "Output",
        "type": "generic",
        "hasGear": true
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_split_3d_vector",
    "name": "Split 3D Vector",
    "category": "operation",
    "folder": "II. Math",
    "description": "Outputs the x, y, and z components of a 3D Vector as three Floating Point Numbers.",
    "inputs": [
      {
        "name": "3D Vector",
        "type": "vector3"
      }
    ],
    "outputs": [
      {
        "name": "X-Component",
        "type": "float"
      },
      {
        "name": "Y-Component",
        "type": "float"
      },
      {
        "name": "Z-Component",
        "type": "float"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_multiplication",
    "name": "Multiplication",
    "category": "operation",
    "folder": "II. Math",
    "description": "Performs multiplication, supporting Floating Point and Integer multiplication.",
    "centerSymbol": "×",
    "inputs": [
      {
        "name": "Input 1",
        "type": "generic",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      },
      {
        "name": "Input 2",
        "type": "generic",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "generic",
        "hasGear": true
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_division",
    "name": "Division",
    "category": "operation",
    "folder": "II. Math",
    "description": "Performs division, supporting Floating Point division and Integer division. Integer division returns the quotient result. The divisor should not be `0`, otherwise it may return an illegal value. When the divisor is `0`, the result is `0`. `-2147483648` divided by `-1` results in `0`.",
    "centerSymbol": "÷",
    "inputs": [
      {
        "name": "Input 1",
        "type": "generic",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      },
      {
        "name": "Input 2",
        "type": "generic",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "generic",
        "hasGear": true
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_create_3d_vector",
    "name": "Create 3D Vector",
    "category": "operation",
    "folder": "II. Math",
    "description": "Creates a 3D Vector from x, y, and z components.",
    "inputs": [
      {
        "name": "X-Component",
        "type": "float",
        "defaultVal": "0.0",
        "placeholder": "0.0"
      },
      {
        "name": "Y-Component",
        "type": "float",
        "defaultVal": "0.0",
        "placeholder": "0.0"
      },
      {
        "name": "Z-Component",
        "type": "float",
        "defaultVal": "0.0",
        "placeholder": "0.0"
      }
    ],
    "outputs": [
      {
        "name": "3D Vector",
        "type": "vector3"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_logarithm_operation",
    "name": "Logarithm Operation",
    "category": "operation",
    "folder": "II. Math",
    "description": "Calculates the logarithm of the argument with the specified base. The base should not be negative or equal to `1`. The argument should not be negative. Otherwise illegal values may be generated.",
    "inputs": [
      {
        "name": "Real Number",
        "type": "float",
        "defaultVal": "0.0",
        "placeholder": "0.0"
      },
      {
        "name": "Base",
        "type": "float",
        "defaultVal": "0.0",
        "placeholder": "0.0"
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "float"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_arccosine_function",
    "name": "Arccosine Function",
    "category": "operation",
    "folder": "II. Math",
    "description": "Calculates the arccosine of the input and returns the value in radians.",
    "inputs": [
      {
        "name": "Input",
        "type": "float",
        "defaultVal": "0.0",
        "placeholder": "0.0"
      }
    ],
    "outputs": [
      {
        "name": "Radian",
        "type": "float"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_arctangent_function",
    "name": "Arctangent Function",
    "category": "operation",
    "folder": "II. Math",
    "description": "Calculates the arctangent of the input and returns the value in radians.",
    "inputs": [
      {
        "name": "Input",
        "type": "float",
        "defaultVal": "0.0",
        "placeholder": "0.0"
      }
    ],
    "outputs": [
      {
        "name": "Radian",
        "type": "float"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_arcsine_function",
    "name": "Arcsine Function",
    "category": "operation",
    "folder": "II. Math",
    "description": "Calculates the arcsine of the input and returns the value in radians.",
    "inputs": [
      {
        "name": "Input",
        "type": "float",
        "defaultVal": "0.0",
        "placeholder": "0.0"
      }
    ],
    "outputs": [
      {
        "name": "Radian",
        "type": "float"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_range_limiting",
    "name": "Range Limiting Operation",
    "category": "operation",
    "folder": "II. Math",
    "description": "Clamps the input value to the range `[lower limit, upper limit]` (both bounds inclusive) and outputs the result. If the input falls within `[lower limit, upper limit]`, returns the original value. If the input is below the lower limit, returns the lower limit. If the input exceeds the upper limit, returns the upper limit. If the lower limit is greater than the upper limit, treats the input as invalid and returns an illegal value.",
    "inputs": [
      {
        "name": "Input",
        "type": "generic",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      },
      {
        "name": "Lower Limit",
        "type": "generic",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      },
      {
        "name": "Upper Limit",
        "type": "generic",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "generic",
        "hasGear": true
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_direction_vector_to_rotation",
    "name": "Direction Vector to Rotation",
    "category": "operation",
    "folder": "II. Math",
    "description": "Converts the Forward Vector and Upward Vector to Euler Angles. Example: For a Character, suppose it has an initial orientation in 3D space. To rotate the character to a desired orientation: The Forward Vector indicates the direction we want the Character's nose to face. The Upward Vector indicates the direction we want the Character's head to point. Output: A 3D Euler rotation vector representing the rotation the Character must undergo to move from its initial orientation to the specified target orientation. **Note:** Ensure the Forward and Upward Vectors are normalized. Using non-normalized vectors can produce unintended scaling and inaccurate rotation results.",
    "inputs": [
      {
        "name": "Forward Vector",
        "type": "vector3",
        "description": "Represents the desired Orientation of the Unit"
      },
      {
        "name": "Upward Vector",
        "type": "vector3",
        "description": "Defines the Unit's Up direction (used to determine the rotation angle). Default is the positive Y-axis of the World Coordinate System"
      }
    ],
    "outputs": [
      {
        "name": "Rotate",
        "type": "vector3",
        "description": "Returns Euler Angles, where each component represents:<br>X – Pitch: Rotation around the local X-axis (right). Controls looking up and down.<br>Y – Yaw: Rotation around the local Y-axis (up). Controls turning left and right.<br>Z – Roll: Rotation around the local Z-axis (forward). Controls tilting the object side to side."
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_calculate_timestamp_from_formatted_time",
    "name": "Calculate Timestamp From Formatted Time",
    "category": "operation",
    "folder": "II. Math",
    "description": "Converts a formatted time to a timestamp.",
    "inputs": [
      {
        "name": "Year",
        "type": "int",
        "defaultVal": "0",
        "placeholder": "0"
      },
      {
        "name": "Month",
        "type": "int",
        "defaultVal": "0",
        "placeholder": "0"
      },
      {
        "name": "Day",
        "type": "int",
        "defaultVal": "0",
        "placeholder": "0"
      },
      {
        "name": "Hour",
        "type": "int",
        "defaultVal": "0",
        "placeholder": "0"
      },
      {
        "name": "Minute",
        "type": "int",
        "defaultVal": "0",
        "placeholder": "0"
      },
      {
        "name": "Second",
        "type": "int",
        "defaultVal": "0",
        "placeholder": "0"
      }
    ],
    "outputs": [
      {
        "name": "Timestamp",
        "type": "int"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_calculate_formatted_time_from_timestamp",
    "name": "Calculate Formatted Time From Timestamp",
    "category": "operation",
    "folder": "II. Math",
    "description": "Converts a timestamp to formatted time.",
    "inputs": [
      {
        "name": "Timestamp",
        "type": "int",
        "defaultVal": "0",
        "placeholder": "0"
      }
    ],
    "outputs": [
      {
        "name": "Year",
        "type": "int"
      },
      {
        "name": "Month",
        "type": "int"
      },
      {
        "name": "Day",
        "type": "int"
      },
      {
        "name": "Hour",
        "type": "int"
      },
      {
        "name": "Minute",
        "type": "int"
      },
      {
        "name": "Second",
        "type": "int"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_calculate_day_of_the_week_from_timestamp",
    "name": "Calculate Day of the Week From Timestamp",
    "category": "operation",
    "folder": "II. Math",
    "description": "Converts a timestamp to the day of the week.",
    "inputs": [
      {
        "name": "Timestamp",
        "type": "int",
        "defaultVal": "0",
        "placeholder": "0"
      }
    ],
    "outputs": [
      {
        "name": "Weekday",
        "type": "int"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_radians_to_degrees",
    "name": "Radians to Degrees",
    "category": "operation",
    "folder": "II. Math",
    "description": "Converts radians to degrees.",
    "inputs": [
      {
        "name": "Radian Value",
        "type": "float",
        "defaultVal": "0.0",
        "placeholder": "0.0"
      }
    ],
    "outputs": [
      {
        "name": "Angle Value",
        "type": "float"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_addition",
    "name": "Addition",
    "category": "operation",
    "folder": "II. Math",
    "description": "Adds two Floating Point Numbers or Integers.",
    "centerSymbol": "+",
    "inputs": [
      {
        "name": "Input 1",
        "type": "generic",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      },
      {
        "name": "Input 2",
        "type": "generic",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "generic",
        "hasGear": true
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_subtraction",
    "name": "Subtraction",
    "category": "operation",
    "folder": "II. Math",
    "description": "Subtracts two Floating Point Numbers or Integers.",
    "centerSymbol": "-",
    "inputs": [
      {
        "name": "Input 1",
        "type": "generic",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      },
      {
        "name": "Input 2",
        "type": "generic",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "generic",
        "hasGear": true
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_degrees_to_radians",
    "name": "Degrees to Radians",
    "category": "operation",
    "folder": "II. Math",
    "description": "Converts degrees to radians.",
    "inputs": [
      {
        "name": "Angle Value",
        "type": "float",
        "defaultVal": "0.0",
        "placeholder": "0.0"
      }
    ],
    "outputs": [
      {
        "name": "Radian Value",
        "type": "float"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_take_larger_value",
    "name": "Take Larger Value",
    "category": "operation",
    "folder": "II. Math",
    "description": "Returns the larger of two inputs.",
    "inputs": [
      {
        "name": "Input 1",
        "type": "generic",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      },
      {
        "name": "Input 2",
        "type": "generic",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      }
    ],
    "outputs": [
      {
        "name": "Larger Value",
        "type": "generic",
        "hasGear": true
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_take_smaller_value",
    "name": "Take Smaller Value",
    "category": "operation",
    "folder": "II. Math",
    "description": "Returns the smaller of two inputs.",
    "inputs": [
      {
        "name": "Input 1",
        "type": "generic",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      },
      {
        "name": "Input 2",
        "type": "generic",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      }
    ],
    "outputs": [
      {
        "name": "Smaller Value",
        "type": "generic",
        "hasGear": true
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_absolute_value_operation",
    "name": "Absolute Value Operation",
    "category": "operation",
    "folder": "II. Math",
    "description": "Returns the absolute value of the input.",
    "inputs": [
      {
        "name": "Input",
        "type": "generic",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "generic",
        "hasGear": true
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_distance_between_two_coordinate_points",
    "name": "Distance Between Two Coordinate Points",
    "category": "operation",
    "folder": "II. Math",
    "description": "Calculates the Euclidean distance between two coordinates.",
    "inputs": [
      {
        "name": "Coordinate Point 1",
        "type": "vector3"
      },
      {
        "name": "Coordinate Point 2",
        "type": "vector3"
      }
    ],
    "outputs": [
      {
        "name": "Distance",
        "type": "float"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_logical_not_operation",
    "name": "Logical NOT Operation",
    "category": "operation",
    "folder": "II. Math",
    "description": "Performs a logical NOT operation on the input Boolean value and returns the result.",
    "inputs": [
      {
        "name": "Input",
        "type": "bool",
        "defaultVal": "True",
        "options": [
          "True",
          "False"
        ]
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "bool"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_logical_or_operation",
    "name": "Logical OR Operation",
    "category": "operation",
    "folder": "II. Math",
    "description": "Performs a logical OR operation on the two input Boolean values and returns the result.",
    "inputs": [
      {
        "name": "Input 1",
        "type": "bool",
        "defaultVal": "True",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "name": "Input 2",
        "type": "bool",
        "defaultVal": "True",
        "options": [
          "True",
          "False"
        ]
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "bool"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_logical_xor_operation",
    "name": "Logical XOR Operation",
    "category": "operation",
    "folder": "II. Math",
    "description": "Performs a logical XOR operation on the two input Boolean values and returns the result.",
    "inputs": [
      {
        "name": "Input 1",
        "type": "bool",
        "defaultVal": "True",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "name": "Input 2",
        "type": "bool",
        "defaultVal": "True",
        "options": [
          "True",
          "False"
        ]
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "bool"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_logical_and",
    "name": "Logical AND Operation",
    "category": "operation",
    "folder": "II. Math",
    "description": "Performs a logical AND operation on the two input Boolean values and returns the result.",
    "inputs": [
      {
        "name": "Input 1",
        "type": "bool",
        "defaultVal": "True",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "name": "Input 2",
        "type": "bool",
        "defaultVal": "True",
        "options": [
          "True",
          "False"
        ]
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "bool"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_exponentiation",
    "name": "Exponentiation",
    "category": "operation",
    "folder": "II. Math",
    "description": "Raises the base to the given exponent and returns the result.",
    "inputs": [
      {
        "name": "Base",
        "type": "generic",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      },
      {
        "name": "Exponent",
        "type": "generic",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "generic",
        "hasGear": true
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_modulo_operation",
    "name": "Modulo Operation",
    "category": "operation",
    "folder": "II. Math",
    "description": "Returns the result of input 1 modulo input 2, with input 1 as the dividend.",
    "centerSymbol": "%",
    "inputs": [
      {
        "name": "Input 1",
        "type": "int",
        "defaultVal": "0",
        "placeholder": "0"
      },
      {
        "name": "Input 2",
        "type": "int",
        "defaultVal": "0",
        "placeholder": "0"
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "int"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_arithmetic_square_root_operation",
    "name": "Arithmetic Square Root Operation",
    "category": "operation",
    "folder": "II. Math",
    "description": "Returns the arithmetic square root of the input value.",
    "inputs": [
      {
        "name": "Input",
        "type": "float",
        "defaultVal": "0.0",
        "placeholder": "0.0"
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "float"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_sign_operation",
    "name": "Sign Operation",
    "category": "operation",
    "folder": "II. Math",
    "description": "When the input is positive, returns `1`. When the input is negative, returns `-1`. When the input is `0`, returns `0`.",
    "inputs": [
      {
        "name": "Input",
        "type": "generic",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "generic",
        "hasGear": true
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_round_to_integer_operation",
    "name": "Round to Integer Operation",
    "category": "operation",
    "folder": "II. Math",
    "description": "Performs a rounding operation based on the rounding method and returns the rounded positive number.",
    "inputs": [
      {
        "name": "Input",
        "type": "float",
        "defaultVal": "0.0",
        "placeholder": "0.0"
      },
      {
        "name": "Rounding Mode",
        "type": "enum",
        "description": "`Round`: Rounds to the nearest integer according to standard rules.<br>`Round Up`: Returns the smallest integer greater than the input value. Example: input `1.2` → `2`; input `-2.3` → `-2`.<br>`Round Down`: Returns the largest integer smaller than the input value. Example: input `1.2` → `1`; input `-2.3` → `-3`.<br>`Truncate`: Removes the decimal part of the floating point number (rounds toward zero). Example: input `1.2` → `1`; input `-2.3` → `-2`."
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "int"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_3d_vector_normalization",
    "name": "3D Vector Normalization",
    "category": "operation",
    "folder": "II. Math",
    "description": "Normalizes the length of a 3D Vector and outputs the result.",
    "inputs": [
      {
        "name": "3D Vector",
        "type": "vector3"
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "vector3"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_3d_vector_addition",
    "name": "3D Vector Addition",
    "category": "operation",
    "folder": "II. Math",
    "description": "Calculates the sum of two 3D Vectors.",
    "inputs": [
      {
        "name": "3D Vector 1",
        "type": "vector3"
      },
      {
        "name": "3D Vector 2",
        "type": "vector3"
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "vector3"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_3d_vector_angle",
    "name": "3D Vector Angle",
    "category": "operation",
    "folder": "II. Math",
    "description": "Calculates the angle between two 3D Vectors and outputs it in radians.",
    "inputs": [
      {
        "name": "3D Vector 1",
        "type": "vector3"
      },
      {
        "name": "3D Vector 2",
        "type": "vector3"
      }
    ],
    "outputs": [
      {
        "name": "Angle (Radians)",
        "type": "float"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_3d_vector_subtraction",
    "name": "3D Vector Subtraction",
    "category": "operation",
    "folder": "II. Math",
    "description": "Calculates the difference of two 3D Vectors.",
    "inputs": [
      {
        "name": "3D Vector 1",
        "type": "vector3"
      },
      {
        "name": "3D Vector 2",
        "type": "vector3"
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "vector3"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_3d_vector_modulo_operation",
    "name": "3D Vector Modulo Operation",
    "category": "operation",
    "folder": "II. Math",
    "description": "Calculates the magnitude of the input 3D Vector.",
    "inputs": [
      {
        "name": "3D Vector",
        "type": "vector3"
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "float"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_3d_vector_dot_product",
    "name": "3D Vector Dot Product",
    "category": "operation",
    "folder": "II. Math",
    "description": "Calculates the dot product of two input 3D Vectors.",
    "inputs": [
      {
        "name": "3D Vector 1",
        "type": "vector3"
      },
      {
        "name": "3D Vector 2",
        "type": "vector3"
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "float"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_3d_vector_zoom",
    "name": "3D Vector Zoom",
    "category": "operation",
    "folder": "II. Math",
    "description": "Scales the input 3D Vector (scalar multiplication) and outputs the result.",
    "inputs": [
      {
        "name": "3D Vector",
        "type": "vector3"
      },
      {
        "name": "Zoom Multiplier",
        "type": "float",
        "defaultVal": "0.0",
        "placeholder": "0.0"
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "vector3"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_3d_vector_cross_product",
    "name": "3D Vector Cross Product",
    "category": "operation",
    "folder": "II. Math",
    "description": "Calculates the cross product of two 3D Vectors.",
    "inputs": [
      {
        "name": "3D Vector 1",
        "type": "vector3"
      },
      {
        "name": "3D Vector 2",
        "type": "vector3"
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "vector3"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_3d_vector_rotation",
    "name": "3D Vector Rotation",
    "category": "operation",
    "folder": "II. Math",
    "description": "Rotates the input 3D Vector by the Euler Angles specified by the rotation and returns the result. **Note:** The Rotated 3D Vector is the one you want to rotate. The Rotated Euler Angles define how the vector should be rotated. The resulting output vector shows the position of the original 3D Vector after applying the rotation.",
    "inputs": [
      {
        "name": "Rotate",
        "type": "vector3",
        "description": "This 3D input vector represents a specific rotation in Euler angles, where each component represents:<br>X – Pitch: Rotation around the local X-axis (right). Controls looking up and down.<br>Y – Yaw: Rotation around the local Y-axis (up). Controls turning left and right.<br>Z – Roll: Rotation around the local Z-axis (forward). Controls tilting the object side to side."
      },
      {
        "name": "Rotated 3D Vector",
        "type": "vector3"
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "vector3"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_greater_than",
    "name": "Greater Than",
    "category": "operation",
    "folder": "II. Math",
    "description": "Returns whether the left value is greater than the right value.",
    "inputs": [
      {
        "name": "Left Value",
        "type": "generic",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      },
      {
        "name": "Right Value",
        "type": "generic",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "bool"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_greater_than_or_equal_to",
    "name": "Greater Than or Equal To",
    "category": "operation",
    "folder": "II. Math",
    "description": "Returns whether the left value is greater than or equal to the right value.",
    "inputs": [
      {
        "name": "Left Value",
        "type": "generic",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      },
      {
        "name": "Right Value",
        "type": "generic",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "bool"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_less_than",
    "name": "Less Than",
    "category": "operation",
    "folder": "II. Math",
    "description": "Returns whether the left value is less than the right value.",
    "inputs": [
      {
        "name": "Left Value",
        "type": "generic",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      },
      {
        "name": "Right Value",
        "type": "generic",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "bool"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_less_than_or_equal_to",
    "name": "Less Than or Equal To",
    "category": "operation",
    "folder": "II. Math",
    "description": "Returns whether the left value is less than or equal to the right value.",
    "inputs": [
      {
        "name": "Left Value",
        "type": "generic",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      },
      {
        "name": "Right Value",
        "type": "generic",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "bool"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_cosine_function",
    "name": "Cosine Function",
    "category": "operation",
    "folder": "II. Math",
    "description": "Calculates the cosine of the input in radians.",
    "inputs": [
      {
        "name": "Radian",
        "type": "float",
        "defaultVal": "0.0",
        "placeholder": "0.0"
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "float"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_pi",
    "name": "Pi",
    "category": "operation",
    "folder": "II. Math",
    "description": "Returns the mathematical constant Pi (π ≈ 3.14159265).",
    "inputs": [],
    "outputs": [
      {
        "name": "Pi (π)",
        "type": "float",
        "description": "Pi value (3.14159265)"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_tangent_function",
    "name": "Tangent Function",
    "category": "operation",
    "folder": "II. Math",
    "description": "Calculates the tangent of the input in radians.",
    "inputs": [
      {
        "name": "Radian",
        "type": "float",
        "defaultVal": "0.0",
        "placeholder": "0.0"
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "float"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_sine_function",
    "name": "Sine Function",
    "category": "operation",
    "folder": "II. Math",
    "description": "Calculates the sine of the input in radians.",
    "inputs": [
      {
        "name": "Radian",
        "type": "float",
        "defaultVal": "0.0",
        "placeholder": "0.0"
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "float"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_left_shift_operation",
    "name": "Left Shift Operation",
    "category": "operation",
    "folder": "II. Math",
    "description": "Performs a logical left shift on the input by the specified bit count and outputs the result.",
    "inputs": [
      {
        "name": "Value",
        "type": "int",
        "defaultVal": "0",
        "placeholder": "0"
      },
      {
        "name": "Left Shift Count",
        "type": "int",
        "defaultVal": "0",
        "placeholder": "0"
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "int"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_right_shift_operation",
    "name": "Right Shift Operation",
    "category": "operation",
    "folder": "II. Math",
    "description": "Performs a logical right shift on the input by the specified bit count and outputs the result. Performs an arithmetic right shift, preserving the sign bit.",
    "inputs": [
      {
        "name": "Value",
        "type": "int",
        "defaultVal": "0",
        "placeholder": "0"
      },
      {
        "name": "Right Shift Count",
        "type": "int",
        "defaultVal": "0",
        "placeholder": "0"
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "int"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_bitwise_and",
    "name": "Bitwise AND",
    "category": "operation",
    "folder": "II. Math",
    "description": "Performs a bitwise AND operation on the two inputs and returns the result.",
    "inputs": [
      {
        "name": "Value 1",
        "type": "int",
        "defaultVal": "0",
        "placeholder": "0"
      },
      {
        "name": "Value 2",
        "type": "int",
        "defaultVal": "0",
        "placeholder": "0"
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "int"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_bitwise_or",
    "name": "Bitwise OR",
    "category": "operation",
    "folder": "II. Math",
    "description": "Performs a bitwise OR operation on the two inputs and returns the result.",
    "inputs": [
      {
        "name": "Value 1",
        "type": "int",
        "defaultVal": "0",
        "placeholder": "0"
      },
      {
        "name": "Value 2",
        "type": "int",
        "defaultVal": "0",
        "placeholder": "0"
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "int"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_xor_exclusive_or",
    "name": "XOR (Exclusive OR)",
    "category": "operation",
    "folder": "II. Math",
    "description": "Performs a bitwise XOR operation on the two inputs and returns the result.",
    "inputs": [
      {
        "name": "Value 1",
        "type": "int",
        "defaultVal": "0",
        "placeholder": "0"
      },
      {
        "name": "Value 2",
        "type": "int",
        "defaultVal": "0",
        "placeholder": "0"
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "int"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_bitwise_complement",
    "name": "Bitwise Complement",
    "category": "operation",
    "folder": "II. Math",
    "description": "Performs a bitwise complement operation on the input and returns the result.",
    "inputs": [
      {
        "name": "Value",
        "type": "int",
        "defaultVal": "0",
        "placeholder": "0"
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "int"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_write_by_bit",
    "name": "Write by bit",
    "category": "operation",
    "folder": "II. Math",
    "description": "Writes the write value as a binary number to the `[start bit, end bit]` of the target value (also a binary number). The start bit is indexed from `0`, and the write length includes both the start and end bits. If the binary significant length of the write value (counted from the first `1` from the left) exceeds the write length, the write fails and returns the original value. If the write value is negative, it also fails due to exceeding the write length (the first bit of a negative number's binary representation is the sign bit `1`).",
    "inputs": [
      {
        "name": "Written value",
        "type": "int",
        "defaultVal": "0",
        "placeholder": "0"
      },
      {
        "name": "Write value",
        "type": "int",
        "defaultVal": "0",
        "placeholder": "0"
      },
      {
        "name": "Write starting position",
        "type": "int",
        "defaultVal": "0",
        "placeholder": "0"
      },
      {
        "name": "Write end position",
        "type": "int",
        "defaultVal": "0",
        "placeholder": "0"
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "int"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_read_by_bit",
    "name": "Read by bit",
    "category": "operation",
    "folder": "II. Math",
    "description": "Reads the value from `[start bit, end bit]` of the value (in binary representation).",
    "inputs": [
      {
        "name": "Value",
        "type": "int",
        "defaultVal": "0",
        "placeholder": "0"
      },
      {
        "name": "Read starting position",
        "type": "int",
        "defaultVal": "0",
        "placeholder": "0"
      },
      {
        "name": "Read end position",
        "type": "int",
        "defaultVal": "0",
        "placeholder": "0"
      }
    ],
    "outputs": [
      {
        "name": "Result",
        "type": "int"
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_create_dictionary",
    "name": "Create Dictionary",
    "category": "operation",
    "folder": "III. Dictionary",
    "description": "Creates Key-Value Pairs sequentially from the input key and value lists. This node builds the Dictionary using the shorter of the key and value lists; extra items are truncated. If duplicate keys are found in the key list, creation fails and returns an empty Dictionary.",
    "inputs": [
      {
        "name": "Key List",
        "type": "generic",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      },
      {
        "name": "Value List",
        "type": "generic",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      }
    ],
    "outputs": [
      {
        "name": "Dictionary",
        "type": "generic",
        "hasGear": true
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_assembly_dictionary",
    "name": "Assembly Dictionary",
    "category": "operation",
    "folder": "III. Dictionary",
    "description": "Combines up to 50 Key-Value Pairs into one Dictionary.",
    "inputs": [
      {
        "name": "Key 0~49",
        "type": "generic",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      },
      {
        "name": "Value 0~49",
        "type": "generic",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      }
    ],
    "outputs": [
      {
        "name": "Dictionary",
        "type": "generic",
        "hasGear": true
      }
    ],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_split_structure",
    "name": "Split Structure",
    "category": "operation",
    "folder": "IV. Structures",
    "description": "Returns all parameters of the specified Structure.",
    "inputs": [
      {
        "name": "Target Structure",
        "type": "generic",
        "defaultVal": "0",
        "placeholder": "0",
        "hasGear": true
      }
    ],
    "outputs": [],
    "execIn": false,
    "execOut": false
  },
  {
    "id": "op_assemble_structure",
    "name": "Assemble Structure",
    "category": "operation",
    "folder": "IV. Structures",
    "description": "Combines multiple parameters into a single Structure-type value.",
    "inputs": [],
    "outputs": [
      {
        "name": "Structure",
        "type": "generic",
        "hasGear": true
      }
    ],
    "execIn": false,
    "execOut": false
  }
];
