const escapeHtml = (value) => String(value).replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));

const reviewSamples = [
  { user: 'Nymf', hours: '18.4 hrs', verdict: 'Recommended', tone: 'positive', date: 'Posted: yesterday', text: 'The hallway starts simple and then quietly gets inside your head. The moment I realized the exit sign was moving, I had to take a break. Excellent little nightmare.', helpful: '142', funny: '38' },
  { user: 'Rui', hours: '3.1 hrs', verdict: 'Recommended', tone: 'positive', date: 'Posted: 3 days ago', text: 'Went in expecting a short puzzle and stayed for the atmosphere. The lighting does so much work here. Bring headphones and do not trust the third hallway.', helpful: '86', funny: '21' },
  { user: 'Aster', hours: '0.7 hrs', verdict: 'Not Recommended', tone: 'negative', date: 'Posted: 5 days ago', text: 'I am sure this is very good at being scary. Unfortunately, I am also very good at being scared.', helpful: '55', funny: '104' }
];

function reviewCard(review) {
  return `<article class="review-card"><div class="review-user"><span class="review-avatar">${review.user[0]}</span><b>${review.user}</b><small>${review.hours}<br>on record</small></div><div class="review-body"><div class="review-title"><span class="review-vote ${review.tone}">${review.tone === 'positive' ? 'Recommended' : 'Not Recommended'}</span><button class="review-star">☆</button></div><small class="review-date">${review.date}</small><p>${escapeHtml(review.text)}</p><div class="review-helpful"><span>Was this review helpful?</span><div><button>▰ Yes</button><button>▾ No</button><button>☺ Funny</button><button>✦ Award</button></div><small>${review.helpful} people found this review helpful · ${review.funny} found this review funny</small></div></div></article>`;
}

export function renderDetailPage(world) {
  return `<div class="detail-page"><header class="detail-header"><button class="back-button" data-action="close-detail">← Back to Browse</button><span class="detail-brand">${escapeHtml(world.title)}</span><button class="close-button" data-action="close-detail">×</button></header><main class="detail-shell"><div class="detail-hero"><img src="${world.image}" alt="${escapeHtml(world.title)}"><div class="detail-hero-copy"><span class="chip">${world.category}</span><h1>${escapeHtml(world.title)}</h1><p>Created by <b>${escapeHtml(world.author)}</b> · updated recently</p></div></div><div class="steam-layout"><aside class="detail-sidebar"><button class="play-button">▶ Play Wonderland</button><button class="secondary-button">＋ Add to collection</button><div class="sidebar-panel"><b>Details</b><dl><dt>Stage GUID</dt><dd><span>${world.guid}</span><button data-action="copy-guid">Copy</button></dd><dt>Players</dt><dd>${world.players}</dd><dt>Average session</dt><dd>${world.time}</dd><dt>Gameplay</dt><dd>${world.type}</dd></dl></div><div class="sidebar-panel leaderboard-sidebar"><div class="sidebar-heading"><b>Leaderboards</b><span class="muted">Top times</span></div>${['Danny & Nymf','yemi & SEVEN','Rui & Koko','Aster & Lumi'].map((name, index) => `<div class="leader-row"><b>${index + 1}</b><span class="avatar">${name[0]}</span><span>${name}</span><strong>${['08:12.44','09:03.17','09:55.02','10:41.88'][index]}</strong></div>`).join('')}</div></aside><section class="detail-main"><div class="review-jump"><div><p class="eyebrow" style="color:#9ab0e0;">Reviews · ${world.reviews} positive</p><h2>What the community says</h2><p><strong>${world.reviewCount}</strong> reviews · <strong>${world.reviews}</strong> recommend this wonderland</p></div><button class="primary-button" data-action="check-reviews">Read reviews</button></div><div class="detail-copy"><h2>About this Wonderland</h2><p>${escapeHtml(world.description)}</p><div class="tag-row">${world.tags.map((tag) => `<span>${tag}</span>`).join('')}</div></div><div class="screenshots"><div class="section-heading"><h2>In-game screenshots</h2><button class="text-button">View gallery ›</button></div><div class="screenshot-grid"><img src="${world.image}" alt=""><img src="${world.image}" alt=""></div></div><div class="reviews-section" id="reviews"><div class="reviews-heading"><div><h2>Reviews</h2><p>${world.reviewCount} reviews total</p></div><div class="overall-review"><small>OVERALL RATING</small><strong>${world.reviews}</strong><span>${world.reviewCount}</span></div></div><div class="review-filters"><button>All reviews</button><button>Positive</button><button>Negative</button><button>Most helpful</button><button>Recent</button><button>Funny</button></div><div class="review-columns"><div><h3>Positive reviews</h3>${reviewSamples.slice(0, 2).map(reviewCard).join('')}</div><div><h3>Negative reviews</h3>${reviewSamples.slice(2).map(reviewCard).join('')}</div></div></div></section></div></main></div>`;
}